name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOTNET_ROLL_FORWARD: Major

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21
    - name: Restore tools
      run: dotnet tool restore
    - name: Begin scan
      if: env.SONAR_TOKEN != null && env.SONAR_TOKEN != ''
      run: dotnet sonarscanner begin /o:"kaliumhexacyanoferrat" /k:"GenHTTP.Website" /d:sonar.token="$SONAR_TOKEN" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.branch.name="${GITHUB_REF##*/}" 
    - name: Build project
      run: dotnet build GenHTTP.Website.sln -c Release
    - name: End scan
      if: env.SONAR_TOKEN != null && env.SONAR_TOKEN != ''
      run: dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
